project:
  type: book
  output-dir: docs

book:
  title: "EDS 220 - Working with Environmental Datasets"
  author: "Carmen Galaz García"
  #date: "October 2023"
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/lesson-1-python-review.qmd

format:
  html:
    theme: cosmo