project:
  type: book
  output-dir: docs
  # set working directory of all files to the main project directory
  # https://quarto.org/docs/projects/code-execution.html
  execute-dir: project

sidebar:
  style: "floating"

book:
  title: "EDS 220 - Working with Environmental Datasets"
  author: "Carmen Galaz García"
  #date: "October 2023"
  chapters:
    - index.qmd
    - lectures/lesson-1-python-review.qmd
    - part: "Tabular data"
      chapters:
        - lectures/lesson-2-series-dataframes.qmd
        - discussion-sections/ds1-anthr-prelim-data-exploration.qmd 
        - lectures/lesson-3-pandas-subsetting.qmd
        - lectures/lesson-4-basic-plotting.qmd
        - lectures/lesson-5-updating-dataframes.qmd
        - lectures/lesson-6-groupby.qmd
        - discussion-sections/ds2-hares.qmd                
        - lectures/lesson-7-time-series.qmd
    - part: "Vector data"
      chapters:
        - lectures/lesson-8-vector-data.qmd
        - lectures/lesson-11-crs.qmd
        - lectures/lesson-9-geopandas-intro.qmd
        - lectures/lesson-10-merge-data.qmd
        - lectures/lesson-12-csv-to-geo.qmd
        - lectures/lesson-13-reproject-and-clip.qmd
        #- lectures/lesson-13-standin.qmd
        - discussion-sections/ds3-earthquakes.qmd
    - part: "Multi-dimensional data"
      chapters:
        - lectures/lesson-14-multidimensional-data.qmd
        - lectures/lesson-15-xarray.qmd
    - part: "Raster data"
      chapters:
        #- lectures/lesson-16-raster-formats.qmd
        - lectures/lesson-17-rioxarray.qmd
        - lectures/lesson-19-dem.qmd
        - discussion-sections/ds4-landcover.qmd
        - lectures/lesson-18-STAC.qmd
        - discussion-sections/ds5-modis-ndvi.qmd
        
      
  appendices:
    - appendices/set-pat.qmd
    - appendices/gitignore_untrack.qmd
    - appendices/undoing-commit.qmd

execute:
  freeze: auto  # re-render only when source changes
  
format:
  html:
    theme: cosmo