project:
  type: book
  output-dir: docs
  # set working directory of all files to the main project directory
  # https://quarto.org/docs/projects/code-execution.html
  execute-dir: project

book:
  title: "EDS 220 - Working with Environmental Datasets"
  author: "Carmen Galaz García"
  #date: "October 2023"
  chapters:
    - index.qmd
    - part: "Lectures"
      chapters:
        - lectures/lesson-1-python-review.qmd
        - lectures/lesson-2-pandas-basics.qmd
    - part: "Discussion Sections"
      chapters:
       - discussion-sections/ds1-anthr-prelim-data-exploration.qmd

execute:
  freeze: auto  # re-render only when source changes
  
format:
  html:
    theme: cosmo