name: mpc-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - geopandas=0.13.2
  - pip=23.3.1
  - matplotlib=3.7.1
  - ipykernel
  - rioxarray=0.14.1
  - numpy=1.24.3
  - contextily=1.4.0
  - pyarrow=11.0.0
  - fsspec=2023.12.0
  - adlfs=2023.10.0
  - geogif=0.1.5
  - planetary-computer=1.0.0
  - pystac-client=0.7.5